---
- hosts: droplets
  sudo: yes
  vars:
    DB_DATABASE:
    DB_USERNAME:
    DB_PASSWORD:

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - mysql-server
      - mysql-client
      - php5-mysql
      - python-mysqldb

  - name: Create MySQL DB
    mysql_db: name={{ DB_DATABASE }} state=present

  - name: Create MySQL User
    mysql_user: name={{ DB_USERNAME }} password={{ DB_PASSWORD }} priv={{ DB_DATEABASE }}*:ALL state=present

    notify:
      - restart php5-fpm
      - restart nginx

  handlers:
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted
